package ru.yandex.practicum.filmorate.db.dao;

import lombok.extern.slf4j.Slf4j;
import org.springframework.dao.EmptyResultDataAccessException;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.core.namedparam.MapSqlParameterSource;
import org.springframework.jdbc.core.namedparam.NamedParameterJdbcTemplate;
import org.springframework.jdbc.core.simple.SimpleJdbcInsert;
import org.springframework.stereotype.Component;
import ru.yandex.practicum.filmorate.model.Film;

import java.sql.Date;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Optional;

@Component
@Slf4j
public class FilmDaoImpL implements FilmDao {
    private final JdbcTemplate jdbcTemplate;

    private NamedParameterJdbcTemplate namedDb;

    public FilmDaoImpL(JdbcTemplate jdbcTemplate) {
        this.jdbcTemplate = jdbcTemplate;
    }

    @Override
    /*
     Returns new film Id which be generated by database
     */
    public int insertFilm(Film film) {
        SimpleJdbcInsert simpleJdbcInsert = new SimpleJdbcInsert(jdbcTemplate)
                .withTableName("film")
                .usingGeneratedKeyColumns("id");
        return simpleJdbcInsert.executeAndReturnKey(mapFilmToMap(film)).intValue();
    }

    @Override
    public void update(Film film) {
        String sql = "UPDATE film SET name = ?, description = ?, release_date = ?, duration = ?, rating_MPA = ? WHERE id = ?";
        jdbcTemplate.update(
                sql,
                film.getName(),
                film.getDescription(),
                film.getReleaseDate(),
                film.getDuration(),
                film.getRatingMpaId(),
                film.getId()
        );
    }

    @Override
    public List<Film> getAllFilms() {
        List<Film> filmList = jdbcTemplate.query(
                "SELECT id, name, description, release_date, duration, rating_MPA  FROM film",
                this::mapRowToFilm
        );
        return filmList;
    }

    @Override
    public Optional<Film> getFilmById(int id) {
        String sql = "SELECT id, name, description, release_date, duration, rating_MPA FROM film WHERE id = ?";
        Optional<Film> film = Optional.empty();
        try {
            film = Optional.ofNullable(jdbcTemplate.queryForObject(sql, this::mapRowToFilm, id));
        } catch (EmptyResultDataAccessException ignored) {
        }
        return film;
    }

    public List<Film> getFilteredFilm(int count, List<Integer> excludeList) {
        namedDb = new NamedParameterJdbcTemplate(jdbcTemplate);

        MapSqlParameterSource parameters = new MapSqlParameterSource("ids", excludeList);
        parameters.addValue("count", count);

        String sql = "SELECT id, name, description, release_date, duration, rating_MPA " +
                "FROM film " +
                (!excludeList.isEmpty() ? "WHERE id NOT IN (:ids) " : "") +
                "LIMIT (:count)";

        List<Film> films = namedDb.query(sql, parameters, this::mapRowToFilm);

        return films;
    }


    private Film mapRowToFilm(ResultSet resultSet, int rowNum) throws SQLException {
        Optional<Date> date = Optional.ofNullable(resultSet.getDate("release_date"));

        return Film.builder()
                .id(resultSet.getInt("id"))
                .name(resultSet.getString("name"))
                .description(resultSet.getString("description"))
                .releaseDate(date
                        .map(Date::toLocalDate)
                        .orElse(null))
                .duration(resultSet.getInt("duration"))
                .ratingMpaId(resultSet.getInt("rating_MPA"))
                .build();
    }

    private Map<String, Object> mapFilmToMap(Film film) {
        Map<String, Object> map = new HashMap<>();
        map.put("id", film.getId());
        map.put("name", film.getName());
        map.put("description", film.getDescription());
        map.put("release_date", film.getReleaseDate());
        map.put("duration", film.getDuration());
        map.put("rating_MPA", film.getRatingMpaId());

        return map;
    }

    public List<Film> getAllFilmsByDirector(int directorId, String sortCodeForDirectorMovies) {
        List<Film> filmList = jdbcTemplate.query(
                "" +
                        "SELECT F.id, F.name, F.description, F.release_date, F.duration, F.rating_MPA " +
                        "FROM film_director FD " +
                        "LEFT JOIN film F on F.ID = FD.film_id " +
                        "LEFT JOIN (" +
                                    "SELECT DISTINCT film_id, " +
                                    "COUNT(user_id) AS LIKECOUNT " +
                                    "FROM film_like " +
                                    "GROUP BY film_id) AS LIKETEMP on FD.film_id = LIKETEMP.film_id " +
                        "WHERE director_ID = ?" +
                        (sortCodeForDirectorMovies.equals("likes") ?
                                "ORDER BY LIKETEMP.LIKECOUNT DESC":
                                "ORDER BY F.release_date ASC"),
                this::mapRowToFilm, directorId
        );
        return filmList;
    }
}

