package ru.yandex.practicum.filmorate.db.dao;

import lombok.extern.slf4j.Slf4j;
import org.springframework.dao.EmptyResultDataAccessException;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.core.namedparam.MapSqlParameterSource;
import org.springframework.jdbc.core.namedparam.NamedParameterJdbcTemplate;
import org.springframework.jdbc.core.simple.SimpleJdbcInsert;
import org.springframework.stereotype.Component;
import ru.yandex.practicum.filmorate.model.Film;

import java.sql.Date;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Optional;

@Component
@Slf4j
public class FilmDaoImpL implements FilmDao {
    private final JdbcTemplate jdbcTemplate;

    private NamedParameterJdbcTemplate namedDb;

    public FilmDaoImpL(JdbcTemplate jdbcTemplate) {
        this.jdbcTemplate = jdbcTemplate;
    }

    @Override
    /*
     Returns new film Id which be generated by database
     */
    public int insertFilm(Film film) {
        SimpleJdbcInsert simpleJdbcInsert = new SimpleJdbcInsert(jdbcTemplate)
                .withTableName("film")
                .usingGeneratedKeyColumns("id");
        return simpleJdbcInsert.executeAndReturnKey(mapFilmToMap(film)).intValue();
    }

    @Override
    public void update(Film film) {
        String sql = "UPDATE film SET name = ?, description = ?, release_date = ?, duration = ?, rating_MPA = ? WHERE id = ?";
        jdbcTemplate.update(
                sql,
                film.getName(),
                film.getDescription(),
                film.getReleaseDate(),
                film.getDuration(),
                film.getRatingMpaId(),
                film.getId()
        );
    }

    @Override
    public List<Film> getAllFilms() {
        List<Film> filmList = jdbcTemplate.query(
                "SELECT id, name, description, release_date, duration, rating_MPA  FROM film",
                this::mapRowToFilm
        );
        return filmList;
    }

    @Override
    public Optional<Film> getFilmById(int id) {
        String sql = "SELECT id, name, description, release_date, duration, rating_MPA FROM film WHERE id = ?";
        Optional<Film> film = Optional.empty();
        try {
            film = Optional.ofNullable(jdbcTemplate.queryForObject(sql, this::mapRowToFilm, id));
        } catch (EmptyResultDataAccessException ignored) {
        }
        return film;
    }

    public List<Film> getFilteredFilm(int count, List<Integer> excludeList, Integer genreId, String year) {
        namedDb = new NamedParameterJdbcTemplate(jdbcTemplate);

        MapSqlParameterSource parameters = new MapSqlParameterSource(Map.of("ids", excludeList));
        parameters.addValue("count", count);
        parameters.addValue("genreId", genreId);
        parameters.addValue("year", year);

        String sql = "SELECT id, name, description, release_date, duration, rating_MPA " +
                "FROM film " +
                "WHERE 1=1 " +
                (!excludeList.isEmpty() ? "AND id NOT IN (:ids) " : "") +
                (genreId == null ? " " : " AND id IN (SELECT film_id FROM film_genre WHERE genre_id = :genreId)") +
                (year == null ? " " : " AND  EXTRACT(YEAR FROM release_date) = :year") +
                " LIMIT (:count)";

        List<Film> films = namedDb.query(sql, parameters, this::mapRowToFilm);

        return films;
    }


    private Film mapRowToFilm(ResultSet resultSet, int rowNum) throws SQLException {
        Optional<Date> date = Optional.ofNullable(resultSet.getDate("release_date"));

        return Film.builder()
                .id(resultSet.getInt("id"))
                .name(resultSet.getString("name"))
                .description(resultSet.getString("description"))
                .releaseDate(date
                        .map(Date::toLocalDate)
                        .orElse(null))
                .duration(resultSet.getInt("duration"))
                .ratingMpaId(resultSet.getInt("rating_MPA"))
                .build();
    }

    private Map<String, Object> mapFilmToMap(Film film) {
        Map<String, Object> map = new HashMap<>();
        map.put("id", film.getId());
        map.put("name", film.getName());
        map.put("description", film.getDescription());
        map.put("release_date", film.getReleaseDate());
        map.put("duration", film.getDuration());
        map.put("rating_MPA", film.getRatingMpaId());

        return map;
    }
}

